FROM node:20.19-slim
RUN apt-get update -qq \
  && apt-get install -y \
     openssh-client git python3 make g++ curl openssh-server build-essential libpq-dev postgresql-contrib

RUN mkdir /code

WORKDIR /code
COPY yarn.lock .
COPY package.json .
RUN yarn install
COPY . /code
RUN chmod +x ./scripts/dev-entrypoint.sh

EXPOSE 3000
ENTRYPOINT ./scripts/dev-entrypoint.sh
